# This is the SAM template that represents the architecture of your serverless application
# https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-sam-template-basics.html

# The AWSTemplateFormatVersion identifies the capabilities of the template
# https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/format-version-structure.html
AWSTemplateFormatVersion: 2010-09-09
Description: >-
  Feedback-template

# Transform section specifies one or more macros that AWS CloudFormation uses to process your template
# https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/transform-section-structure.html
Transform:
- AWS::Serverless-2016-10-31

Parameters:
  BotName:
    Type: String
    Default: "Concierge-Bot-Feedback"
    Description: "The name of the feedback bot to be deployed"
  IntentName:
    Type: String
    Default: "captureFeedback"
    Description: "The name of the default intent for capturing feedback"
  
# Resources declares the AWS resources that you want to include in the stack
# https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/resources-section-structure.html
Resources:
  # Each Lambda function is defined by properties:
  # https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction

  # This is a Lambda function config associated with the source code: hello-from-lambda.js
  helloFromLambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/hello-from-lambda.helloFromLambdaHandler
      Runtime: nodejs12.x
      MemorySize: 128
      Timeout: 100
      Description: A Lambda function that returns a static string.
      Policies:
        # Give Lambda basic execution Permission to the helloFromLambda
        - AWSLambdaBasicExecutionRole
  
  conciergeBot:
      Type: Custom::LexIntent
      Properties:
        ServiceToken:
          Fn::ImportValue: "cfn-lex-intent-1-0-3-ServiceToken"
        name:
          Ref: "IntentName"
        confirmationPrompt:
          maxAttempts: 1
          messages:
            - content: "Should I order  your {Crust} crust {Type} pizza with {Sauce} sauce?"
              contentType": "PlainText"
        fulfillmentActivity:
          type: "ReturnIntent"
        rejectionStatement:
          messages":
            - content: "Ok, I'll cancel your order."
              contentType: "PlainText"
            - content: "I cancelled your order."
              contentType: "PlainText"
        sampleUtterances:
          - "Order me a pizza."
          - "Order me a {Type} pizza."
          - "I want a {Crust} crust {Type} pizza"
          - "I want a {Crust} crust {Type} pizza with {Sauce} sauce."